// Package db is photosort's state: the images and their stage results, cloud batches, jobs and job items.
//
// It runs on SQLite (a file in the workdir, the default) or Postgres (PHOTOSORT_DB=postgres://...). Both share one
// schema and nearly all SQL; Dialect covers the rest. An existing SQLite database from the Python version opens as
// is and is migrated in place.
package db

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"
)

// DB is the database handle. Safe for concurrent use.
type DB struct {
	SQL *sql.DB
	D   Dialect
	// SQLite allows one writer at a time; serializing them here keeps writers from racing into SQLITE_BUSY (readers
	// never wait: WAL). Postgres needs no such lock.
	wmu sync.Mutex
}

// DefaultFile is the SQLite file inside the workdir.
const DefaultFile = "photosort.db"

// URL resolves the database to open: PHOTOSORT_DB if set, else the SQLite file in the workdir.
func URL(workdir string) string {
	if u := os.Getenv("PHOTOSORT_DB"); u != "" {
		return u
	}
	return "sqlite://" + filepath.Join(workdir, DefaultFile)
}

// Open connects and brings the schema up to date. url is postgres://... / postgresql://..., sqlite://<path>, or a
// bare file path.
func Open(url string) (*DB, error) {
	var d *DB
	switch {
	case strings.HasPrefix(url, "postgres://") || strings.HasPrefix(url, "postgresql://"):
		s, err := sql.Open("pgx", url)
		if err != nil {
			return nil, err
		}
		s.SetMaxOpenConns(16)
		d = &DB{SQL: s, D: Dialect{PG: true}}
	default:
		path := strings.TrimPrefix(url, "sqlite://")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		dsn := "file:" + path + "?_pragma=busy_timeout(30000)&_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)"
		s, err := sql.Open("sqlite", dsn)
		if err != nil {
			return nil, err
		}
		s.SetMaxOpenConns(8)
		d = &DB{SQL: s, D: Dialect{}}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := d.SQL.PingContext(ctx); err != nil {
		d.SQL.Close()
		return nil, err
	}
	if err := d.migrate(); err != nil {
		d.SQL.Close()
		return nil, fmt.Errorf("migrating the database: %w", err)
	}
	return d, nil
}

// Close closes the connection pool.
func (d *DB) Close() error { return d.SQL.Close() }

// Kind is "sqlite" or "postgres".
func (d *DB) Kind() string {
	if d.D.PG {
		return "postgres"
	}
	return "sqlite"
}

// Now is the current time as seconds since the epoch, as stored.
func Now() float64 { return float64(time.Now().UnixNano()) / 1e9 }

// Exec runs a statement written with ? placeholders.
func (d *DB) Exec(q string, args ...any) (sql.Result, error) {
	if !d.D.PG {
		d.wmu.Lock()
		defer d.wmu.Unlock()
	}
	return d.SQL.Exec(d.D.Rebind(q), args...)
}

// Query runs a query written with ? placeholders.
func (d *DB) Query(q string, args ...any) (*sql.Rows, error) {
	return d.SQL.Query(d.D.Rebind(q), args...)
}

// QueryRow runs a single-row query written with ? placeholders.
func (d *DB) QueryRow(q string, args ...any) *sql.Row {
	return d.SQL.QueryRow(d.D.Rebind(q), args...)
}

// Tx is a transaction whose statements take ? placeholders.
type Tx struct {
	tx *sql.Tx
	D  Dialect
}

func (t *Tx) Exec(q string, args ...any) (sql.Result, error) {
	return t.tx.Exec(t.D.Rebind(q), args...)
}
func (t *Tx) Query(q string, args ...any) (*sql.Rows, error) {
	return t.tx.Query(t.D.Rebind(q), args...)
}
func (t *Tx) QueryRow(q string, args ...any) *sql.Row { return t.tx.QueryRow(t.D.Rebind(q), args...) }

// Write runs fn in a transaction, committing when it returns nil.
func (d *DB) Write(fn func(*Tx) error) error {
	if !d.D.PG {
		d.wmu.Lock()
		defer d.wmu.Unlock()
	}
	tx, err := d.SQL.Begin()
	if err != nil {
		return err
	}
	if err := fn(&Tx{tx, d.D}); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

func affected(r sql.Result, err error) (int64, error) {
	if err != nil {
		return 0, err
	}
	return r.RowsAffected()
}

// ---- schema -------------------------------------------------------------------------------------------------------

func (d *DB) schema() string {
	id, js, real := "INTEGER PRIMARY KEY", "TEXT", "REAL"
	if d.D.PG {
		id, js, real = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "JSONB", "DOUBLE PRECISION"
	}
	r := strings.NewReplacer("$ID", id, "$JSON", js, "$REAL", real)
	return r.Replace(`
CREATE TABLE IF NOT EXISTS images (
  id $ID,
  path TEXT UNIQUE NOT NULL,
  folder TEXT,
  size BIGINT, mtime $REAL,
  local_json $JSON,          -- stage 1 result
  batch_id TEXT,             -- cloud batch this image was submitted in
  vlm_json $JSON,            -- stage 2 parsed result
  vlm_usage $JSON,           -- token usage
  vlm_skip TEXT,             -- why a job left it for the vision model (e.g. local tier 0); cleared when either stage reruns
  override_json $JSON,       -- manual corrections from the UI
  error TEXT,
  local_at $REAL, vlm_at $REAL
);
CREATE TABLE IF NOT EXISTS batches (
  id TEXT PRIMARY KEY,
  backend TEXT, model TEXT, n INTEGER,
  created $REAL, state TEXT, fetched INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS jobs (
  id $ID,
  created $REAL, started $REAL, finished $REAL,
  state TEXT,                -- queued | running | preempting | cancelling | done | cancelled | failed
  stage TEXT,                -- scan | local | vlm | done
  paths_json $JSON, options_json $JSON,
  total INTEGER DEFAULT 0, done INTEGER DEFAULT 0, errors INTEGER DEFAULT 0,
  message TEXT
);
CREATE TABLE IF NOT EXISTS job_items (
  id $ID,
  job_id BIGINT, image_id BIGINT,
  stage TEXT,                -- local | vlm
  started $REAL, finished $REAL, seconds $REAL,   -- finished is NULL while the image is in flight
  error TEXT,
  usage_json $JSON           -- vlm token usage and timings
);
CREATE INDEX IF NOT EXISTS idx_job_items ON job_items(job_id, id);
CREATE INDEX IF NOT EXISTS idx_batch ON images(batch_id);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON jobs(state);
CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY);
`)
}

// Columns added after the first release. An old database gets them on open.
func (d *DB) migrations() [][3]string {
	js, real := "TEXT", "REAL"
	if d.D.PG {
		js, real = "JSONB", "DOUBLE PRECISION"
	}
	return [][3]string{
		{"images", "folder", "TEXT"}, {"images", "override_json", js},
		{"images", "local_at", real}, {"images", "vlm_at", real}, {"images", "lr_json", js}, {"images", "truth_json", js},
		{"images", "vlm_skip", "TEXT"},
		{"jobs", "stages_json", js}, // per-stage timings and settings, written as the job moves through them
		{"jobs", "owner", "TEXT"}, {"jobs", "heartbeat", real},
		{"jobs", "lane", "TEXT"}, {"jobs", "priority", "INTEGER DEFAULT 0"},
	}
}

func (d *DB) version(tx *Tx) (int, error) {
	var v sql.NullInt64
	if err := tx.QueryRow("SELECT MAX(version) FROM schema_migrations").Scan(&v); err != nil {
		return 0, err
	}
	if v.Valid {
		return int(v.Int64), nil
	}
	if !d.D.PG {
		// Databases from the Python version kept the version in SQLite's user_version.
		var uv int
		if err := tx.QueryRow("PRAGMA user_version").Scan(&uv); err != nil {
			return 0, err
		}
		return uv, nil
	}
	return 0, nil
}

func (d *DB) migrate() error {
	return d.Write(func(tx *Tx) error {
		for _, stmt := range strings.Split(d.schema(), ";\n") {
			if s := strings.TrimSpace(stmt); s != "" {
				if _, err := tx.Exec(s); err != nil {
					return fmt.Errorf("%w in %s", err, s)
				}
			}
		}
		for _, t := range []string{"images", "jobs"} {
			cols, err := d.columnsTx(tx, t)
			if err != nil {
				return err
			}
			for _, m := range d.migrations() {
				if m[0] == t && !cols[m[1]] {
					if _, err := tx.Exec(fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s", m[0], m[1], m[2])); err != nil {
						return err
					}
				}
			}
		}
		if err := backfillFolders(tx); err != nil {
			return err
		}
		v, err := d.version(tx)
		if err != nil {
			return err
		}
		if v < 1 {
			if err := d.fourTiers(tx); err != nil {
				return err
			}
		}
		if _, err := tx.Exec("INSERT INTO schema_migrations(version) VALUES (1) ON CONFLICT DO NOTHING"); err != nil {
			return err
		}
		if !d.D.PG {
			if _, err := tx.Exec("PRAGMA user_version = 1"); err != nil {
				return err
			}
		}
		// After the migrations: they add the columns these index.
		if _, err := tx.Exec("CREATE INDEX IF NOT EXISTS idx_folder ON images(folder)"); err != nil {
			return err
		}
		// The dashboard groups by these expressions on every poll; indexed, the database reads the index instead of
		// parsing each row's JSON. One pair per focus_source, so switching it in the config stays fast.
		for _, src := range FocusSources {
			sfx := ""
			if src != "vlm" {
				sfx = "_" + src
			}
			// The Python version's indexes spelled the expression differently, so queries never matched them.
			for _, old := range []string{"idx_final_tier" + sfx, "idx_tier_lr" + sfx} {
				if _, err := tx.Exec("DROP INDEX IF EXISTS " + old); err != nil {
					return err
				}
			}
			sfx = "_v2" + sfx
			expr := d.D.FinalTier(src)
			for _, q := range []string{
				fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_final_tier%s ON images((%s)) WHERE local_json IS NOT NULL", sfx, expr),
				fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_tier_lr%s ON images((%s), (%s)) WHERE local_json IS NOT NULL",
					sfx, expr, d.D.JNum("lr_json", "rating")),
			} {
				if _, err := tx.Exec(q); err != nil {
					return fmt.Errorf("%w in %s", err, q)
				}
			}
		}
		return nil
	})
}

func (d *DB) columnsTx(tx *Tx, table string) (map[string]bool, error) {
	q := fmt.Sprintf("SELECT name FROM pragma_table_info('%s')", table)
	if d.D.PG {
		q = fmt.Sprintf("SELECT column_name FROM information_schema.columns WHERE table_name = '%s' AND table_schema = current_schema()", table)
	}
	rows, err := tx.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := map[string]bool{}
	for rows.Next() {
		var n string
		if err := rows.Scan(&n); err != nil {
			return nil, err
		}
		out[n] = true
	}
	return out, rows.Err()
}

func backfillFolders(tx *Tx) error {
	rows, err := tx.Query("SELECT id, path FROM images WHERE folder IS NULL")
	if err != nil {
		return err
	}
	type pair struct {
		id   int64
		path string
	}
	var todo []pair
	for rows.Next() {
		var p pair
		if err := rows.Scan(&p.id, &p.path); err != nil {
			rows.Close()
			return err
		}
		todo = append(todo, p)
	}
	rows.Close()
	for _, p := range todo {
		if _, err := tx.Exec("UPDATE images SET folder=? WHERE id=?", filepath.Dir(p.path), p.id); err != nil {
			return err
		}
	}
	return nil
}

// fourTiers: focus went from three tiers (0 none, 1 partial, 2 sharp; rating 3 = banger) to four (0 miss, 1 soft,
// 2 slightly soft, 3 sharp; rating 4 = banger). Old tiers keep their color: 2 -> 3 (green), 1 -> 2 (yellow), banger
// 3 -> 4 (blue); orange (1) is the new slot. `photosort rescore` then re-derives the local tiers properly.
func (d *DB) fourTiers(tx *Tx) error {
	for _, cp := range [][2]string{{"local_json", "local_tier"}, {"vlm_json", "focus_tier"}, {"override_json", "focus_tier"},
		{"override_json", "rating"}, {"truth_json", "focus_tier"}} {
		col, key := cp[0], cp[1]
		v := d.D.JNum(col, key)
		up := fmt.Sprintf("CASE %s WHEN 1 THEN 2 WHEN 2 THEN 3 WHEN 3 THEN 4 ELSE %s END", v, v)
		q := fmt.Sprintf("UPDATE images SET %s = %s WHERE %s IN (1, 2, 3)", col, d.D.SetJPath(col, []string{key}, up), v)
		if _, err := tx.Exec(q); err != nil {
			return err
		}
	}
	return nil
}

// ErrNotFound is returned for a missing row.
var ErrNotFound = errors.New("not found")
